# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

transformYCpp <- function(Zr) {
    .Call('_JACA_transformYCpp', PACKAGE = 'JACA', Zr)
}

jacaCpp <- function(Y, X_list, lambda, rho, W_list = NULL, kmax = 500L, eps = 0.000001, verbose = FALSE) {
    .Call('_JACA_jacaCpp', PACKAGE = 'JACA', Y, X_list, lambda, rho, W_list, kmax, eps, verbose)
}

